### ISSUE TITLE
Setup Connection Issue

### ISSUE THREAD

**Issue by shajji1** [mojaloop/pathfinder-query-client#10]
**You must have setup connection to the @@mojaloop npm repo on JFrog in order to install.** No Docs or link provide for this purpose, Please help.

**Comment by HenkKodde** [comment]
Hi @shajji1  - will be looking into your issue. Can you please confirm if you execute "npm install @mojaloop/pathfinder-query-client" successfully as indicated in the readme.md doc?

**Comment by HenkKodde** [comment]
Please confirm the installation process/guide you have/are following.

**Comment by shajji1** [comment]
Hi, Sorry i was not well and didn't check mail in previous days, yes i execute this command "npm install @mojaloop/pathfinder-query-client" and get this response

`-- @mojaloop/pathfinder-query-client@0.2.0  +-- bluebird@3.5.0  `-- native-dns-packet@0.1.1    +-- buffercursor@0.0.12    | `-- verror@1.10.0    |   +-- assert-plus@1.0.0    |   +-- core-util-is@1.0.2    |   `-- extsprintf@1.4.0    `-- ipaddr.js@1.8.1
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Shuja\Desktop\New folder (2)\package.json'npm WARN New folder (2) No descriptionnpm WARN New folder (2) No repository field.npm WARN New folder (2) No README datanpm WARN New folder (2) No license field.
I think it is successfully installed.

I also run this "node query.js 923153926550" command at "C:\Users\Shuja\Desktop\New folder (2)\node_modules\@mojaloop\pathfinder-query-client\examples" directory. i get same response "The source IP is not authorized to access PathFinder"
May be i'm not authorize to access pathfinder due to this point "You must have setup connection to the @leveloneproject npm repo on JFrog in order to install". So can you tell me what the purpose of this point and how can i create setup connection with repo on jfrog.

Regards,
Shuja    On Wednesday, 5 December 2018, 23:33:48 GMT+5, HenkKodde <notifications@github.com> wrote:  
 
 
Hi @shajji1 - will be looking into your issue. Can you please confirm if you execute "npm install @mojaloop/pathfinder-query-client" successfully as indicated in the readme.md doc?

**Comment by shajji1** [comment]
Hi, Sorry i was not well and didn't check in previous 2 days, yes i execute this command "npm install @mojaloop/pathfinder-query-client" and it is successfully installed.

I also run this "**node query.js 923153926550**" command at "**C:\Users\Mypc\Desktop\New folder (2)\node_modules\@mojaloop\pathfinder-query-client\examples**" directory. i get same response "The source IP is not authorized to access PathFinder"
May be i'm not authorize to access pathfinder due to this point "**You must have setup connection to the @LevelOneProject npm repo on JFrog in order to install**". So can you tell me what the purpose of this point and how can i create setup connection with repo on jfrog.

**Comment by shajji1** [comment]
and 1 more thing this IP **156.154.59.228**, is this only for example purpose?

**Comment by shajji1** [comment]
Hi @ksatya77, Yes i'm trying to connect with actual pathfinder and getting unauthorized to access Pathfinder error, and please tell that i'm using correct IP "**156.154.59.228**" or not

**Comment by ksatya77** [comment]
You cannot connect to the actual pathfinder unless your source is whitelisted on their end. Can you please give us some context on why you are trying to connect to the actual pathfinder. If this is for testing purposes, you can use the mock-pathfinder. It has the same interface.

**Comment by shajji1** [comment]
because i have leveloneproject repository and i can't find mock-pathfinder for that.

**Comment by ksatya77** [comment]
https://github.com/mojaloop/mock-pathfinder

**Comment by HenkKodde** [comment]
Hi @shajji1 - please let us know if this has resolved your issue?

**Comment by shajji1** [comment]
i successfully access to mock-pathfinder, but what are the steps required to access actual pathfinder and how to white-list my IP on their end.

**Comment by HenkKodde** [comment]
Your IP needs to be whitelisted on Pathfinder side. I also believe there would be a cost associated, as per there website - https://web.archive.org/web/20100328125711/http://gsmworld.com/our-work/programmes-and-initiatives/pathfinder/.

**Comment by shajji1** [comment]
thnx @HenkKodde & @ksatya77 for help.
if anyone get this issue in future.
Download [mock-pathfinder](https://github.com/mojaloop/mock-pathfinder) as @ksatya77 said.
then run command **npm install** in mock-pathfinder directory to install dependencies.
after this update Database_URI in mock-pathfinder/src/lib/config.js.
this issue is resolved for me so i'm closing this issue, but getting new error on central-directory. https://github.com/mojaloop/central-directory/issues/18
